name: Test Helm Env

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl -s https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Set HELM environment variable
        run: echo "HELM=$(which helm)" >> $GITHUB_ENV

      - name: Check Helm version
        run: |
          echo "Helm binary location: $HELM"
          $HELM version
